---
title: "Project Proposal"
author: "Standard Deviants - Ava Exelbirt, Yura Heo, Claire Li"
format: pdf
execute: 
  warning: false
  message: false
editor: visual
---

```{r}
#| label: load-pkg-data
library(tidyverse)
library(tidymodels)
# add other packages as needed

# add code to load data
sports <- read.csv("data/sports.csv")
```

## Introduction

-   an introduction to the subject matter you're investigating (citing any relevant literature)

-   the motivation for your research question (citing any relevant literature)

-   the primary research question you are interested in exploring

    In the school year 2019 - 2020, how can we predict the revenue in USD of collegiate sports using participation rate, sport type, expenditure, gender, total count of students, and

-   your team's hypotheses regarding the research question

    -   This is a narrative about what you think regarding the research question, not formal statistical hypotheses.

...

## Data description

The data set was taken from TidyTuesday and was originally scraped from Equity in Athletics Data Analysis (EADA), a sector of the US Department of Education. The data is available on an online database found on the (EADA) website[^1].

[^1]: <https://ope.ed.gov/athletics/#/datafile/list>

This data is submitted annually from colleges to the EADA. All co-educational postsecondary institutions that receive Title IV funding that have intercollegiate athletics programs are required by the Equity in Athletics Disclosure Act to submit this data[^2]. The original data files are also created immediately after the data collection for each school. These data are collected annually starting from 2003 to 2022, but for our specific data analysis we will only look at data taken from the school year of 2019. The csv file from Tidy Tuesday contains thousands of observations from years 2015-2019, but we have adjusted the data file to only include year 2019 as this is our population we are analyzing.

[^2]: <https://knightnewhousedata.org/about-the-data#:~:text=The%20data%20is%20available%20via,student%20aid%20programs>)

The dataset we will use from the data scraped on Tidy Tuesday include many observations regarding collegiate sports. These observations include variables such as the name of the city which a school is in, the state, the school name, the classification of the school (like whether it is NCAA Division I, II, or III), the sector name of the school (like 4 year accredited university), sport, and many quantitative variables regarding characteristics about the specific school and their collegiate spending. Most of the quantitative variables are split between men and women, having two different observations for the same variable. For example, there is total male population, total female population, participation rate of women, participation rate of men, participation rate for coed sports for men, participation rate for coed sports for women, revenue for men, revenue for women, expenditures for men, and expenditures for women. There are also observations for the total amount for each of these above variables which includes both men and women; for example, total expenditures for both men and women together. The observations are therefore both quantitative and categorical and measure characteristics of different school's spending, revenue, populations, locations, and sports. 

## Initial exploratory data analysis

-   distribution of the response variable

-   distributions of one potential quantitative predictor variable and one potential categorical predictor variable

-   the relationships between the response variable and each of the predictors from the previous step

-   a potential interaction effect you're interested in exploring (it doesn't have to be an interaction with the two predictors from above)

...

## Analysis approach

-   a description of the response variable and list of all potential predictors

-   regression model technique (multiple linear regression or logistic regression)

...

## Data dictionary

The data dictionary can be found [here](ADD%20LINK!!!) \[Update the link and remove this note!\]

Submit a data dictionary for all the variables in your data set in the `README` of the `data` folder. You do [not]{.underline} need to include the data dictionary in the PDF document.
