---
title: "College's predicted profit by sport"
author: "Standard Deviants - Ava Exelbirt, Yura Heo, Claire Li"
date: "11/7/2023"
format: pdf
execute: 
  warning: false
  message: false
  echo: false
editor: visual
---

```{r}
#| label: load packages and data

```

#### Introduction and data

In our research project, we aim to investigate and understand the factors influencing the profit generated by collegiate sport, specifically basketball, in the school year 2019 to 2020. We will be utilizing a dataset sourced from Tidy Tuesday, which provides a comprehensive collection of observations related to collegiate sports, including information about the schools, classifications, sport types, and various quantitative variables describing the sport players and the schools\' financial investment in sports programs in the dataset called \"sports.csv\". Our primary motivation for this research is to gain insights into the determinants of collegiate basketball profit, which can be of significant interest to educational institutions and further local policy makers and sports enthusiasts. Understanding the factors that contribute to profit generation in collegiate basketball sports can inform decision-making, investment strategies in sports, and future planning for universities and colleges involved in sports programs. We chose to do profit as our response variable because expenditures and revenue are closely related, so expenditure would overpower the other predictor variables if we were to predict revenue or expenditure. Therefore, we will create a new variable, profit calculated from revenue minus expenditures and predict this. 

	Our primary research question is as follows: **In the school year 2019 to 2020, how can we predict the profit (revenue- expenditure) in USD of the collegiate sport basketball using participation rate, school sector name, gender, total count of students, and school classification name.**

Our hypothesis is as follows: **Participation rate, sector name, and gender will be the most influential predictors for the total profit generated by the collegiate sport basketball in USD.**

The data set was taken from TidyTuesday and was originally scraped from Equity in Athletics Data Analysis (EADA), a sector of the US Department of Education. The data is available on an online database found on the (EADA) website1.

This data is submitted annually from colleges to the EADA. All co-educational postsecondary institutions that receive Title IV funding that have intercollegiate athletics programs are required by the Equity in Athletics Disclosure Act to submit this data. The original data files are also created immediately after the data collection for each school. These data are collected annually starting from 2003 to 2022, but for our specific data analysis we will only look at data taken from the school year of 2019 by cleaning the data to a new csv file which we will use for the rest of the project. The csv file from Tidy Tuesday contains thousands of observations from years 2015-2019, but we have adjusted the data file to only include the year 2019 and will filter the data to only include basketball as a sport, as this is our population we are analyzing.

The dataset we will use from the data scraped on Tidy Tuesday include many observations regarding collegiate sports. These observations include variables such as the name of the city which a school is in, the state, the school name, the classification of the school (like whether it is NCAA Division I, II, or III), the type/sector name of the school (like 4 year accredited university), sport, and many quantitative variables regarding characteristics about the specific school and their collegiate spending. Most of the quantitative variables are split between men and women, having two different observations for the same variable. For example, there is total male population, total female population, participation rate of women, participation rate of men, participation rate for coed sports for men, participation rate for coed sports for women, revenue for men, revenue for women, expenditures for men, and expenditures for women. There are also observations for the total amount for each of these above variables which includes both men and women; for example, total expenditures for both men and women together. The observations are therefore both quantitative and categorical and measure characteristics of different school's spending, revenue, populations, locations, and sports.

	The key variables we will use are **participation rate** which is the percentage of students who participate in sports, **sector school name** which is the type of school for example, public, 4-year or above, **gender** which is Male or Female for the context of this data, **total count of students** which is the total amount of students enrolled in the college, and **school classification name** which is a school\'s sports classification for example NCAA Division I-FCS. Then, our response variable is **profit** which is calculated by the total revenue of the school for basketball minus the expenditures of the school for basketball.

#### Methodology

This section includes a brief description of your modeling process. Explain the reasoning for the type of model you\'re fitting, predictor variables considered for the model including any interactions. Additionally, show how you arrived at the final model by describing the model selection process, any variable transformations (if needed), and any other relevant considerations that were part of the model fitting process.

#### Results

In this section, you will output the final model and include a brief discussion of the model assumptions, diagnostics, and any relevant model fit statistics.

This section also includes initial interpretations and conclusions drawn from the model.

::: callout-important
Before you submit, make sure your code chunks are turned off with `echo: false` and there are no warnings or messages with `warning: false` and `message: false` in the YAML.
:::
